#pragma once

#include <cstdint>

/*
 * Step 14 -- forward-declared enums. See task.md for the spec.
 *
 * This header forward-declares the scoped enum `state` and the
 * functions that operate on it. The full enumerator list and the
 * function bodies live in solution.cpp.
 *
 * Do not edit this file. Your work goes in solution.cpp.
 */

namespace task14
{

/* Forward declaration. The underlying type (std::uint8_t) is visible
 * here, which is what makes the forward declaration legal. The
 * enumerator list is intentionally not exposed -- callers don't need
 * it. */
enum class state : std::uint8_t;

state make_idle();
state make_running();
state make_done();

bool is_terminal(state s);

const char *name_of(state s);

}
